### ISSUE TITLE
DisallowedModelAdminLookup

### ISSUE THREAD

**Issue by jedie** [boxine/django-huey-monitor#135]
![image](https://github.com/boxine/django-huey-monitor/assets/71315/d30761f3-01d6-482e-9cc3-5ff751d16c73)

**Comment by jedie** [comment]
Django Bug: https://code.djangoproject.com/ticket/35020  https://github.com/django/django/pull/16661

**Comment by bethe410** [comment]
Hello, there are still errors in "Task Signals": DisallowedModelAdminLookup at /admin/huey_monitor/signalinfomodel/
But in "Task" it's fixed, maybe "Task Signals" should be fixed by the same way?
![image](https://github.com/boxine/django-huey-monitor/assets/119160745/886ae043-2113-4d26-8759-33b42957ea2f)
